# Generated by Django 5.2.11 on 2026-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety_app", "0002_profile_userlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
